spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_auth
    username: postgres
    password:

  jpa:
    hibarnate:
      ddl-auto: update
    show-sql: true

  application:
    name: authservice

security:
  jwt:
    secret-key: jwt-secret-here
    expiration: 3600000 # 1 hour
