spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/db_auth
        username: postgres
        password:

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    application:
        name: authservice

security:
    jwt:
        secret-key: tuXpuB7iwxDLz7GFl999mJvolS2ezzzsEQ2Zk7n9RJA=
        expiration: 3600000 # 1 hour
